#!/usr/bin/env perl

use FindBin;
# add local lib directory
use lib "$FindBin::Bin/lib";
use Getopt::Long;

use App::DeleteOldData;

=item
Prints script usage
=cut

sub usage() {
    print <<USAGE;
Usage: $0 [options] <path>

Deletes all data in an hourly partitioned hierarchy older than
some number of days.  <path> is the base location of the hourly
partitioned data.

Options:
  -h --help                      Show this help message and exit.
  -d --older-than-days=<days>    Drop data older than this number of days.
                                 [default: 10]
  -D --dataset-name=<name>       Only delete data for this dataset name.
                                 If this is not given, all datasets will be
                                 pruned of old data.
  -n --dry-run                   Don't actually do anything, just output the
                                 directories that would have data deleted.
USAGE
}

sub main() {
usage();

}

my $rc = main();
exit $rc;
